# PingTab v1.1.5

# Interval: Ping Measurement interval in seconds
Interval: 3

# EnabledByDefault: If the PingTab is enabled to players by default, notice that
#                   if you enable this setting, it will override any permission
#                   setting you have done.
EnabledByDefault: false

# GoodPing: Pings below this number will be printed as green in the /ping command
GoodPing: 200

# MediumPing: Pings below this number will be printed as gold in the /ping command
#             If the ping gets over this number, it will be printed in red 
MediumPing: 500

# AlertPlayers: Alert players about high latency (Default: true)
AlertPlayers: true

# AlertThreshold: Players with the ping higher than this will be alerted
AlertThreshold: 500

# AlertInterval: The interval, in minutes, for the alerts to be sent
AlertInterval: 5

# AlertMessage: The message that will be sent to the user on the alert event.
#               Color codes are supported using & character.
#               Parameters: %playername - Player Name
#                           %ping - Ping Measured
#                           %threshold - Threshold Set
AlertMessage: "%playername, your latency of %ping is above %threshold!"